swagger: '2.0'
info:
  version: 1.0.0
  title: Simple Spring Boot API
  description: A simple API to illustrate Spring Boot and REST concepts

definitions:
  Employee:
    properties:
      id:
        type: integer
      name:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      role:
        type: string


  Order:
    properties:
      id:
        type: integer
      description:
        type: string
      status:
        # is this an object?
        type: object

tags:
  - name: employees
  - name: orders


paths:

  '/employees':
    get:
      tags:
        - employees
      description: returns a list of all employees
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Employee'
        '400':
          description: bad request

    post:
      tags:
        - employees
      description: creates a new employee
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              firstName:
                type: string
              lastName:
                type: string
              role:
                type: string
      responses:
        '200':
          description: created
        '400':
          description: invalid method

  '/employees/{id}':
    get:
      tags:
        - employees
      description: returns a specific employee based on their id
      parameters:
        - in: path
          name: id
          type: integer
          required: true
          description: the id of the user to be returned

      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Employee'
        '400':
          description: invalid method
        '404':
          description: user not found

    put:
      tags:
        - employees
      description: updates a employee based on their id
      parameters:
        - in: path
          name: id
          type: integer
          required: true

        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              firstName:
                type: string
              lastName:
                type: string
              role:
                type: string

      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Employee'
        '400':
          description: invalid method
        '404':
          description: user not found

    delete:
      tags:
        - employees
      description: deletes a employee based on their id
      parameters:
        - in: path
          name: id
          type: integer
          required: true

      responses:
        '204':
          description: OK but no content is returned
        '404':
          description: user not found

  '/orders':
    get:
      tags:
        - orders
      description: returns a list of all orders
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Order'
        '400':
          description: bad request

    post:
      tags:
        - orders
      description: creates a new order
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/Order'
      responses:
        200:
          description: order created

  '/orders/{id}':
    get:
      tags:
        - orders
      description: returns a specific order based on its id
      parameters:
        - in: path
          name: id
          type: integer
          required: true

      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Order'
        '400':
          description: bad request
        '404':
          description: order not found

  '/orders/{id}/cancel':
    delete:
      tags:
        - orders
      description: deletes an order
      parameters:
        - in: path
          name: id
          type: integer
          required: true

      responses:
        '204':
          description: OK
        '404':
          description: order not found

  '/orders/{id}/complete':
    put:
      tags:
        - orders
      description: updates an order
      parameters:
        - in: path
          name: id
          type: integer
          required: true

        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/Order'

      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Order'
        '400':
          description: bad request
        '404':
          description: order not found










